### ISSUE TITLE
Nitpicking w/ subsetting module

### ISSUE THREAD

**Issue by alexcengler** [UrbanInstitute/pyspark-tutorials#1]
Can you add 'is equal to' and 'is not equal to' to the logical operators used in the subsetting module?  
Also can we change the name to 'filter' instead? That matches the R module and is the word that SparkR and PySpark seem to want to use.

**Comment by levyjeff** [comment]
The objection I have to calling it 'filter' is that there are actually multiple commands that all take subsets of the data, and even 'filter' is often replaced in pySpark with the alias 'where'.  The actual commands it goes over are 'select', 'drop', 'filter/where' and 'sample'.  Maybe a bit more discussion on this language at the top would be warranted?

Sarah was planning to rename the R tutorial to 'subsetting' too.
