### ISSUE TITLE
Data access on AWS S3

### ISSUE THREAD

**Issue by sabman** [UrbanInstitute/pyspark-tutorials#3]
Hi there! thanks for making this public. I'm wondering if the Data is accessible. while trying to run [Spark-Basics-1](https://github.com/UrbanInstitute/pyspark-tutorials/blob/master/pyspark-basics-2.ipynb) notebook the S3 bucket seems to be inaccessible. E.g. `s3://ui-spark-data/Performance_2015Q1.txt`

**Comment by sabman** [comment]
looks fixed by 9bdc8d3abb1ab52a6caeb4258fafade10f4b2c66

**Comment by sabman** [comment]
Thanks @alexcengler

**Comment by rahuldas99** [comment]
Hi Shoaib,

Can you share the file with me on my gmail account i.e.  - rahuldas99@gmail.com . I am learning PySpark , so i need this data and I have no idea about AWS. So kindly share the file if you have it with you..

**Comment by peterotool** [comment]
Hi everyone,

Please, can someone share the file on google drive :)

Thanks in advance !

**Comment by nuria** [comment]
You can download the file like: curl  https://s3.amazonaws.com/ui-spark-social-science-public/data/Performance_2015Q1.txt > social_science.txt
